name: Checks

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  composer-dependency-analyser:
    uses: ./.github/workflows/composer-dependency-analyser.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml
